<?php

namespace App\Posttype;
use Bandco\Core\PostTypeRegister;

class CptReferences extends PostTypeRegister
{

    protected bool $isDisabled = false;
    protected bool $activeGutenberg = true;
    protected string $singular = 'Référence';
    protected string $plural = 'Références';
    protected string $slug = 'references';
    protected bool $isFemale = true;
    protected bool $disableSingle = false;
    protected bool $disableArchivePage = false;
    protected bool $optionPageForArchive = true;

    protected array $labels = [];
    protected array $extraArgs = [];

    public function __construct()
    {
        // Vérifie si la classe parente a un constructeur avant de l'appeler
        if (method_exists(parent::class, '__construct')) {
            parent::__construct();
        }

        $this->labels = [
            'name'               => __('Références'),
            'singular_name'      => __('Référence'),
            'add_new'            => __('Ajouter une référence'),
            'all_items'          => __('Toutes les références'),
            'view_item'          => __('Voir la référence'),
            'view_items'         => __('Voir les références'),
            'add_new_item'       => __('Ajouter'),
            'edit_item'          => __('Éditer la référence'),
            'update_item'        => __('Modifier la référence'),
            'search_items'       => __('Rechercher une référence'),
        ];

        $this->extraArgs = [
            'menu_icon' => 'dashicons-star-filled',
            'labels'    => $this->labels,
        ];
    }
    public function hooks()
    {
        parent::hooks(); // TODO: Change the autogenerated stub
        
    }
}
