<?php

namespace App\Posttype;
use Bandco\Core\PostTypeRegister;

class CptReusableBlock extends PostTypeRegister
{

    protected bool $isDisabled = false;
    protected bool $activeGutenberg = true;
    protected string $singular = 'Bloc réutilisable';
    protected string $plural = 'Blocs réutilisables';
    protected string $slug = 'reusable_block';
    protected bool $disableSingle = true;
    protected bool $disableArchivePage = true;

    protected array $labels = [];
    protected array $extraArgs = [];

    public function __construct()
    {
        // Vérifie si la classe parente a un constructeur avant de l'appeler
        if (method_exists(parent::class, '__construct')) {
            parent::__construct();
        }

        $this->labels = [
            'name'               => __('Blocs réutilisables'),
            'singular_name'      => __('Bloc réutilisable'),
            'add_new'            => __('Ajouter un bloc réutilisable'),
            'all_items'          => __('Tous les blocs réutilisables'),
            'view_item'          => __('Voir le bloc réutilisable'),
            'view_items'         => __('Voir les blocs réutilisables'),
            'add_new_item'       => __('Ajouter un bloc réutilisable'),
            'edit_item'          => __('Modifier le bloc réutilisable'),
            'update_item'        => __('Modifier le bloc réutilisable'),
            'search_items'       => __('Rechercher un bloc réutilisable'),
        ];

        $this->extraArgs = [
            'menu_icon' => 'dashicons-admin-post',
            'labels'    => $this->labels,
        ];
    }
    public function hooks()
    {
        parent::hooks(); // TODO: Change the autogenerated stub
    }
}
